"""Add unique constraint to chapter_num per novel

Revision ID: 6eb75b30879c
Revises: 
Create Date: 2025-07-09 18:08:10.673120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb75b30879c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_novel_chapter_num', ['novel_id', 'chapter_num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint('uq_novel_chapter_num', type_='unique')

    # ### end Alembic commands ###
